"""'followers'

Revision ID: 632bfcf746fb
Revises: 7ab0bd83f242
Create Date: 2020-08-27 16:27:22.907810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '632bfcf746fb'
down_revision = '7ab0bd83f242'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
